// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ef5dcca4-9006-4d9d-84b1-16e4ef44a8ac";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onReadSPO2ButtonChange();
void onReadTemperatureButtonChange();

float temperatura;
int value_heartRate;
int value_spo2;
bool readSPO2_Button;
bool readTemperature_Button;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(value_heartRate, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(value_spo2, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(readSPO2_Button, READWRITE, ON_CHANGE, onReadSPO2ButtonChange);
  ArduinoCloud.addProperty(readTemperature_Button, READWRITE, ON_CHANGE, onReadTemperatureButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
